# roles/network/tasks/main.yml
---
- name: Install Cilium CLI
  shell: |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
    CLI_ARCH=amd64
    if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz
    sudo tar xzwfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
    rm cilium-linux-${CLI_ARCH}.tar.gz
  args:
    creates: /usr/local/bin/cilium

- name: Install Cilium CNI (WireGuard Mode)
  shell: |
    cilium install \
      --version 1.14.5 \
      --set encryption.enabled=true \
      --set encryption.type=wireguard \
      --set l7Proxy=false \
      --set tunnel=geneve
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: cluster.network_mode == 'cilium-wireguard'

- name: Enable Hubble UI
  shell: cilium hubble enable --ui
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: infrastructure.enable_hubble
