apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-supervisor-egress
  namespace: interactive-test
spec:
  podSelector:
    matchLabels:
      app: aiops-supervisor
  policyTypes:
  - Egress
  egress:
  - {} # Allow all egress traffic
