apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      nodeSelector:
        kubernetes.io/hostname: master-oci
      containers:
      - name: web-ui
        image: ghcr.io/jth0809/hybrid-web-ui:latest
        ports:
        - containerPort: 3000
        env:
        - name: SLM_URL
          value: "http://slm-server:11434"
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
  namespace: default
spec:
  selector:
    app: web-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
