apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  namespace: default
data:
  openclaw.json: |
      "agents": {
        "defaults": {
          "models": {
            "primary": "openai/google/gemma-3-1b-it",
            "fallbacks": []
          },
          "llm": {
            "baseURL": "http://vllm-server:8000/v1",
            "apiKey": "none"
          },
          "workspace": "/root/.openclaw/workspace",
          "sandbox": {
            "mode": "none"
          }
        }
      }
    }
